# Generated by Django 5.2.1 on 2025-06-09 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('level', 'Досягнення рівня'), ('accuracy', 'Точність'), ('streak', 'Серія правильних відповідей'), ('tests_completed', 'Кількість тестів')], max_length=20)),
                ('requirement_value', models.IntegerField()),
                ('experience_reward', models.IntegerField(default=50)),
                ('icon', models.CharField(default='award', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('interval_type', models.CharField(blank=True, max_length=20, null=True)),
                ('base_note', models.CharField(blank=True, max_length=5, null=True)),
                ('target_note', models.CharField(blank=True, max_length=5, null=True)),
                ('harmonic_audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('melodic_audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('target_frequency', models.FloatField(blank=True, null=True)),
                ('target_note_name', models.CharField(blank=True, max_length=10, null=True)),
                ('reference_audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('user_answer', models.CharField(blank=True, max_length=50, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_frequency', models.FloatField(blank=True, null=True)),
                ('frequency_tolerance', models.FloatField(default=10.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.testsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
