# Generated by Django 5.2.3 on 2026-02-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_achievement_testquestion_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('experimenter', 'Experimenter')], default='user', max_length=20),
        ),
    ]
